package com.xqx.ych.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class EnrollExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ych_enroll
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ych_enroll
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ych_enroll
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_enroll
     *
     * @mbggenerated
     */
    public EnrollExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_enroll
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_enroll
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_enroll
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_enroll
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_enroll
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_enroll
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_enroll
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_enroll
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_enroll
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_enroll
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ych_enroll
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andEnrollIdIsNull() {
            addCriterion("enroll_id is null");
            return (Criteria) this;
        }

        public Criteria andEnrollIdIsNotNull() {
            addCriterion("enroll_id is not null");
            return (Criteria) this;
        }

        public Criteria andEnrollIdEqualTo(String value) {
            addCriterion("enroll_id =", value, "enrollId");
            return (Criteria) this;
        }

        public Criteria andEnrollIdNotEqualTo(String value) {
            addCriterion("enroll_id <>", value, "enrollId");
            return (Criteria) this;
        }

        public Criteria andEnrollIdGreaterThan(String value) {
            addCriterion("enroll_id >", value, "enrollId");
            return (Criteria) this;
        }

        public Criteria andEnrollIdGreaterThanOrEqualTo(String value) {
            addCriterion("enroll_id >=", value, "enrollId");
            return (Criteria) this;
        }

        public Criteria andEnrollIdLessThan(String value) {
            addCriterion("enroll_id <", value, "enrollId");
            return (Criteria) this;
        }

        public Criteria andEnrollIdLessThanOrEqualTo(String value) {
            addCriterion("enroll_id <=", value, "enrollId");
            return (Criteria) this;
        }

        public Criteria andEnrollIdLike(String value) {
            addCriterion("enroll_id like", value, "enrollId");
            return (Criteria) this;
        }

        public Criteria andEnrollIdNotLike(String value) {
            addCriterion("enroll_id not like", value, "enrollId");
            return (Criteria) this;
        }

        public Criteria andEnrollIdIn(List<String> values) {
            addCriterion("enroll_id in", values, "enrollId");
            return (Criteria) this;
        }

        public Criteria andEnrollIdNotIn(List<String> values) {
            addCriterion("enroll_id not in", values, "enrollId");
            return (Criteria) this;
        }

        public Criteria andEnrollIdBetween(String value1, String value2) {
            addCriterion("enroll_id between", value1, value2, "enrollId");
            return (Criteria) this;
        }

        public Criteria andEnrollIdNotBetween(String value1, String value2) {
            addCriterion("enroll_id not between", value1, value2, "enrollId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andEnrollStatusIsNull() {
            addCriterion("enroll_status is null");
            return (Criteria) this;
        }

        public Criteria andEnrollStatusIsNotNull() {
            addCriterion("enroll_status is not null");
            return (Criteria) this;
        }

        public Criteria andEnrollStatusEqualTo(String value) {
            addCriterion("enroll_status =", value, "enrollStatus");
            return (Criteria) this;
        }

        public Criteria andEnrollStatusNotEqualTo(String value) {
            addCriterion("enroll_status <>", value, "enrollStatus");
            return (Criteria) this;
        }

        public Criteria andEnrollStatusGreaterThan(String value) {
            addCriterion("enroll_status >", value, "enrollStatus");
            return (Criteria) this;
        }

        public Criteria andEnrollStatusGreaterThanOrEqualTo(String value) {
            addCriterion("enroll_status >=", value, "enrollStatus");
            return (Criteria) this;
        }

        public Criteria andEnrollStatusLessThan(String value) {
            addCriterion("enroll_status <", value, "enrollStatus");
            return (Criteria) this;
        }

        public Criteria andEnrollStatusLessThanOrEqualTo(String value) {
            addCriterion("enroll_status <=", value, "enrollStatus");
            return (Criteria) this;
        }

        public Criteria andEnrollStatusLike(String value) {
            addCriterion("enroll_status like", value, "enrollStatus");
            return (Criteria) this;
        }

        public Criteria andEnrollStatusNotLike(String value) {
            addCriterion("enroll_status not like", value, "enrollStatus");
            return (Criteria) this;
        }

        public Criteria andEnrollStatusIn(List<String> values) {
            addCriterion("enroll_status in", values, "enrollStatus");
            return (Criteria) this;
        }

        public Criteria andEnrollStatusNotIn(List<String> values) {
            addCriterion("enroll_status not in", values, "enrollStatus");
            return (Criteria) this;
        }

        public Criteria andEnrollStatusBetween(String value1, String value2) {
            addCriterion("enroll_status between", value1, value2, "enrollStatus");
            return (Criteria) this;
        }

        public Criteria andEnrollStatusNotBetween(String value1, String value2) {
            addCriterion("enroll_status not between", value1, value2, "enrollStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusIsNull() {
            addCriterion("pay_status is null");
            return (Criteria) this;
        }

        public Criteria andPayStatusIsNotNull() {
            addCriterion("pay_status is not null");
            return (Criteria) this;
        }

        public Criteria andPayStatusEqualTo(String value) {
            addCriterion("pay_status =", value, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusNotEqualTo(String value) {
            addCriterion("pay_status <>", value, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusGreaterThan(String value) {
            addCriterion("pay_status >", value, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusGreaterThanOrEqualTo(String value) {
            addCriterion("pay_status >=", value, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusLessThan(String value) {
            addCriterion("pay_status <", value, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusLessThanOrEqualTo(String value) {
            addCriterion("pay_status <=", value, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusLike(String value) {
            addCriterion("pay_status like", value, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusNotLike(String value) {
            addCriterion("pay_status not like", value, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusIn(List<String> values) {
            addCriterion("pay_status in", values, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusNotIn(List<String> values) {
            addCriterion("pay_status not in", values, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusBetween(String value1, String value2) {
            addCriterion("pay_status between", value1, value2, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusNotBetween(String value1, String value2) {
            addCriterion("pay_status not between", value1, value2, "payStatus");
            return (Criteria) this;
        }

        public Criteria andShippingStatusIsNull() {
            addCriterion("shipping_status is null");
            return (Criteria) this;
        }

        public Criteria andShippingStatusIsNotNull() {
            addCriterion("shipping_status is not null");
            return (Criteria) this;
        }

        public Criteria andShippingStatusEqualTo(String value) {
            addCriterion("shipping_status =", value, "shippingStatus");
            return (Criteria) this;
        }

        public Criteria andShippingStatusNotEqualTo(String value) {
            addCriterion("shipping_status <>", value, "shippingStatus");
            return (Criteria) this;
        }

        public Criteria andShippingStatusGreaterThan(String value) {
            addCriterion("shipping_status >", value, "shippingStatus");
            return (Criteria) this;
        }

        public Criteria andShippingStatusGreaterThanOrEqualTo(String value) {
            addCriterion("shipping_status >=", value, "shippingStatus");
            return (Criteria) this;
        }

        public Criteria andShippingStatusLessThan(String value) {
            addCriterion("shipping_status <", value, "shippingStatus");
            return (Criteria) this;
        }

        public Criteria andShippingStatusLessThanOrEqualTo(String value) {
            addCriterion("shipping_status <=", value, "shippingStatus");
            return (Criteria) this;
        }

        public Criteria andShippingStatusLike(String value) {
            addCriterion("shipping_status like", value, "shippingStatus");
            return (Criteria) this;
        }

        public Criteria andShippingStatusNotLike(String value) {
            addCriterion("shipping_status not like", value, "shippingStatus");
            return (Criteria) this;
        }

        public Criteria andShippingStatusIn(List<String> values) {
            addCriterion("shipping_status in", values, "shippingStatus");
            return (Criteria) this;
        }

        public Criteria andShippingStatusNotIn(List<String> values) {
            addCriterion("shipping_status not in", values, "shippingStatus");
            return (Criteria) this;
        }

        public Criteria andShippingStatusBetween(String value1, String value2) {
            addCriterion("shipping_status between", value1, value2, "shippingStatus");
            return (Criteria) this;
        }

        public Criteria andShippingStatusNotBetween(String value1, String value2) {
            addCriterion("shipping_status not between", value1, value2, "shippingStatus");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andConsigneeIsNull() {
            addCriterion("consignee is null");
            return (Criteria) this;
        }

        public Criteria andConsigneeIsNotNull() {
            addCriterion("consignee is not null");
            return (Criteria) this;
        }

        public Criteria andConsigneeEqualTo(String value) {
            addCriterion("consignee =", value, "consignee");
            return (Criteria) this;
        }

        public Criteria andConsigneeNotEqualTo(String value) {
            addCriterion("consignee <>", value, "consignee");
            return (Criteria) this;
        }

        public Criteria andConsigneeGreaterThan(String value) {
            addCriterion("consignee >", value, "consignee");
            return (Criteria) this;
        }

        public Criteria andConsigneeGreaterThanOrEqualTo(String value) {
            addCriterion("consignee >=", value, "consignee");
            return (Criteria) this;
        }

        public Criteria andConsigneeLessThan(String value) {
            addCriterion("consignee <", value, "consignee");
            return (Criteria) this;
        }

        public Criteria andConsigneeLessThanOrEqualTo(String value) {
            addCriterion("consignee <=", value, "consignee");
            return (Criteria) this;
        }

        public Criteria andConsigneeLike(String value) {
            addCriterion("consignee like", value, "consignee");
            return (Criteria) this;
        }

        public Criteria andConsigneeNotLike(String value) {
            addCriterion("consignee not like", value, "consignee");
            return (Criteria) this;
        }

        public Criteria andConsigneeIn(List<String> values) {
            addCriterion("consignee in", values, "consignee");
            return (Criteria) this;
        }

        public Criteria andConsigneeNotIn(List<String> values) {
            addCriterion("consignee not in", values, "consignee");
            return (Criteria) this;
        }

        public Criteria andConsigneeBetween(String value1, String value2) {
            addCriterion("consignee between", value1, value2, "consignee");
            return (Criteria) this;
        }

        public Criteria andConsigneeNotBetween(String value1, String value2) {
            addCriterion("consignee not between", value1, value2, "consignee");
            return (Criteria) this;
        }

        public Criteria andOrgMajorIdIsNull() {
            addCriterion("org_major_id is null");
            return (Criteria) this;
        }

        public Criteria andOrgMajorIdIsNotNull() {
            addCriterion("org_major_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrgMajorIdEqualTo(Integer value) {
            addCriterion("org_major_id =", value, "orgMajorId");
            return (Criteria) this;
        }

        public Criteria andOrgMajorIdNotEqualTo(Integer value) {
            addCriterion("org_major_id <>", value, "orgMajorId");
            return (Criteria) this;
        }

        public Criteria andOrgMajorIdGreaterThan(Integer value) {
            addCriterion("org_major_id >", value, "orgMajorId");
            return (Criteria) this;
        }

        public Criteria andOrgMajorIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("org_major_id >=", value, "orgMajorId");
            return (Criteria) this;
        }

        public Criteria andOrgMajorIdLessThan(Integer value) {
            addCriterion("org_major_id <", value, "orgMajorId");
            return (Criteria) this;
        }

        public Criteria andOrgMajorIdLessThanOrEqualTo(Integer value) {
            addCriterion("org_major_id <=", value, "orgMajorId");
            return (Criteria) this;
        }

        public Criteria andOrgMajorIdIn(List<Integer> values) {
            addCriterion("org_major_id in", values, "orgMajorId");
            return (Criteria) this;
        }

        public Criteria andOrgMajorIdNotIn(List<Integer> values) {
            addCriterion("org_major_id not in", values, "orgMajorId");
            return (Criteria) this;
        }

        public Criteria andOrgMajorIdBetween(Integer value1, Integer value2) {
            addCriterion("org_major_id between", value1, value2, "orgMajorId");
            return (Criteria) this;
        }

        public Criteria andOrgMajorIdNotBetween(Integer value1, Integer value2) {
            addCriterion("org_major_id not between", value1, value2, "orgMajorId");
            return (Criteria) this;
        }

        public Criteria andOrgMajorNumberIsNull() {
            addCriterion("org_major_number is null");
            return (Criteria) this;
        }

        public Criteria andOrgMajorNumberIsNotNull() {
            addCriterion("org_major_number is not null");
            return (Criteria) this;
        }

        public Criteria andOrgMajorNumberEqualTo(Integer value) {
            addCriterion("org_major_number =", value, "orgMajorNumber");
            return (Criteria) this;
        }

        public Criteria andOrgMajorNumberNotEqualTo(Integer value) {
            addCriterion("org_major_number <>", value, "orgMajorNumber");
            return (Criteria) this;
        }

        public Criteria andOrgMajorNumberGreaterThan(Integer value) {
            addCriterion("org_major_number >", value, "orgMajorNumber");
            return (Criteria) this;
        }

        public Criteria andOrgMajorNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("org_major_number >=", value, "orgMajorNumber");
            return (Criteria) this;
        }

        public Criteria andOrgMajorNumberLessThan(Integer value) {
            addCriterion("org_major_number <", value, "orgMajorNumber");
            return (Criteria) this;
        }

        public Criteria andOrgMajorNumberLessThanOrEqualTo(Integer value) {
            addCriterion("org_major_number <=", value, "orgMajorNumber");
            return (Criteria) this;
        }

        public Criteria andOrgMajorNumberIn(List<Integer> values) {
            addCriterion("org_major_number in", values, "orgMajorNumber");
            return (Criteria) this;
        }

        public Criteria andOrgMajorNumberNotIn(List<Integer> values) {
            addCriterion("org_major_number not in", values, "orgMajorNumber");
            return (Criteria) this;
        }

        public Criteria andOrgMajorNumberBetween(Integer value1, Integer value2) {
            addCriterion("org_major_number between", value1, value2, "orgMajorNumber");
            return (Criteria) this;
        }

        public Criteria andOrgMajorNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("org_major_number not between", value1, value2, "orgMajorNumber");
            return (Criteria) this;
        }

        public Criteria andOrgMajorTuitionIsNull() {
            addCriterion("org_major_tuition is null");
            return (Criteria) this;
        }

        public Criteria andOrgMajorTuitionIsNotNull() {
            addCriterion("org_major_tuition is not null");
            return (Criteria) this;
        }

        public Criteria andOrgMajorTuitionEqualTo(BigDecimal value) {
            addCriterion("org_major_tuition =", value, "orgMajorTuition");
            return (Criteria) this;
        }

        public Criteria andOrgMajorTuitionNotEqualTo(BigDecimal value) {
            addCriterion("org_major_tuition <>", value, "orgMajorTuition");
            return (Criteria) this;
        }

        public Criteria andOrgMajorTuitionGreaterThan(BigDecimal value) {
            addCriterion("org_major_tuition >", value, "orgMajorTuition");
            return (Criteria) this;
        }

        public Criteria andOrgMajorTuitionGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("org_major_tuition >=", value, "orgMajorTuition");
            return (Criteria) this;
        }

        public Criteria andOrgMajorTuitionLessThan(BigDecimal value) {
            addCriterion("org_major_tuition <", value, "orgMajorTuition");
            return (Criteria) this;
        }

        public Criteria andOrgMajorTuitionLessThanOrEqualTo(BigDecimal value) {
            addCriterion("org_major_tuition <=", value, "orgMajorTuition");
            return (Criteria) this;
        }

        public Criteria andOrgMajorTuitionIn(List<BigDecimal> values) {
            addCriterion("org_major_tuition in", values, "orgMajorTuition");
            return (Criteria) this;
        }

        public Criteria andOrgMajorTuitionNotIn(List<BigDecimal> values) {
            addCriterion("org_major_tuition not in", values, "orgMajorTuition");
            return (Criteria) this;
        }

        public Criteria andOrgMajorTuitionBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("org_major_tuition between", value1, value2, "orgMajorTuition");
            return (Criteria) this;
        }

        public Criteria andOrgMajorTuitionNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("org_major_tuition not between", value1, value2, "orgMajorTuition");
            return (Criteria) this;
        }

        public Criteria andGrantAccountIsNull() {
            addCriterion("grant_account is null");
            return (Criteria) this;
        }

        public Criteria andGrantAccountIsNotNull() {
            addCriterion("grant_account is not null");
            return (Criteria) this;
        }

        public Criteria andGrantAccountEqualTo(BigDecimal value) {
            addCriterion("grant_account =", value, "grantAccount");
            return (Criteria) this;
        }

        public Criteria andGrantAccountNotEqualTo(BigDecimal value) {
            addCriterion("grant_account <>", value, "grantAccount");
            return (Criteria) this;
        }

        public Criteria andGrantAccountGreaterThan(BigDecimal value) {
            addCriterion("grant_account >", value, "grantAccount");
            return (Criteria) this;
        }

        public Criteria andGrantAccountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("grant_account >=", value, "grantAccount");
            return (Criteria) this;
        }

        public Criteria andGrantAccountLessThan(BigDecimal value) {
            addCriterion("grant_account <", value, "grantAccount");
            return (Criteria) this;
        }

        public Criteria andGrantAccountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("grant_account <=", value, "grantAccount");
            return (Criteria) this;
        }

        public Criteria andGrantAccountIn(List<BigDecimal> values) {
            addCriterion("grant_account in", values, "grantAccount");
            return (Criteria) this;
        }

        public Criteria andGrantAccountNotIn(List<BigDecimal> values) {
            addCriterion("grant_account not in", values, "grantAccount");
            return (Criteria) this;
        }

        public Criteria andGrantAccountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("grant_account between", value1, value2, "grantAccount");
            return (Criteria) this;
        }

        public Criteria andGrantAccountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("grant_account not between", value1, value2, "grantAccount");
            return (Criteria) this;
        }

        public Criteria andCouponIdIsNull() {
            addCriterion("coupon_id is null");
            return (Criteria) this;
        }

        public Criteria andCouponIdIsNotNull() {
            addCriterion("coupon_id is not null");
            return (Criteria) this;
        }

        public Criteria andCouponIdEqualTo(String value) {
            addCriterion("coupon_id =", value, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdNotEqualTo(String value) {
            addCriterion("coupon_id <>", value, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdGreaterThan(String value) {
            addCriterion("coupon_id >", value, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdGreaterThanOrEqualTo(String value) {
            addCriterion("coupon_id >=", value, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdLessThan(String value) {
            addCriterion("coupon_id <", value, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdLessThanOrEqualTo(String value) {
            addCriterion("coupon_id <=", value, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdLike(String value) {
            addCriterion("coupon_id like", value, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdNotLike(String value) {
            addCriterion("coupon_id not like", value, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdIn(List<String> values) {
            addCriterion("coupon_id in", values, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdNotIn(List<String> values) {
            addCriterion("coupon_id not in", values, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdBetween(String value1, String value2) {
            addCriterion("coupon_id between", value1, value2, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdNotBetween(String value1, String value2) {
            addCriterion("coupon_id not between", value1, value2, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponPaidIsNull() {
            addCriterion("coupon_paid is null");
            return (Criteria) this;
        }

        public Criteria andCouponPaidIsNotNull() {
            addCriterion("coupon_paid is not null");
            return (Criteria) this;
        }

        public Criteria andCouponPaidEqualTo(BigDecimal value) {
            addCriterion("coupon_paid =", value, "couponPaid");
            return (Criteria) this;
        }

        public Criteria andCouponPaidNotEqualTo(BigDecimal value) {
            addCriterion("coupon_paid <>", value, "couponPaid");
            return (Criteria) this;
        }

        public Criteria andCouponPaidGreaterThan(BigDecimal value) {
            addCriterion("coupon_paid >", value, "couponPaid");
            return (Criteria) this;
        }

        public Criteria andCouponPaidGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("coupon_paid >=", value, "couponPaid");
            return (Criteria) this;
        }

        public Criteria andCouponPaidLessThan(BigDecimal value) {
            addCriterion("coupon_paid <", value, "couponPaid");
            return (Criteria) this;
        }

        public Criteria andCouponPaidLessThanOrEqualTo(BigDecimal value) {
            addCriterion("coupon_paid <=", value, "couponPaid");
            return (Criteria) this;
        }

        public Criteria andCouponPaidIn(List<BigDecimal> values) {
            addCriterion("coupon_paid in", values, "couponPaid");
            return (Criteria) this;
        }

        public Criteria andCouponPaidNotIn(List<BigDecimal> values) {
            addCriterion("coupon_paid not in", values, "couponPaid");
            return (Criteria) this;
        }

        public Criteria andCouponPaidBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("coupon_paid between", value1, value2, "couponPaid");
            return (Criteria) this;
        }

        public Criteria andCouponPaidNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("coupon_paid not between", value1, value2, "couponPaid");
            return (Criteria) this;
        }

        public Criteria andEnrollAccountIsNull() {
            addCriterion("enroll_account is null");
            return (Criteria) this;
        }

        public Criteria andEnrollAccountIsNotNull() {
            addCriterion("enroll_account is not null");
            return (Criteria) this;
        }

        public Criteria andEnrollAccountEqualTo(BigDecimal value) {
            addCriterion("enroll_account =", value, "enrollAccount");
            return (Criteria) this;
        }

        public Criteria andEnrollAccountNotEqualTo(BigDecimal value) {
            addCriterion("enroll_account <>", value, "enrollAccount");
            return (Criteria) this;
        }

        public Criteria andEnrollAccountGreaterThan(BigDecimal value) {
            addCriterion("enroll_account >", value, "enrollAccount");
            return (Criteria) this;
        }

        public Criteria andEnrollAccountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("enroll_account >=", value, "enrollAccount");
            return (Criteria) this;
        }

        public Criteria andEnrollAccountLessThan(BigDecimal value) {
            addCriterion("enroll_account <", value, "enrollAccount");
            return (Criteria) this;
        }

        public Criteria andEnrollAccountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("enroll_account <=", value, "enrollAccount");
            return (Criteria) this;
        }

        public Criteria andEnrollAccountIn(List<BigDecimal> values) {
            addCriterion("enroll_account in", values, "enrollAccount");
            return (Criteria) this;
        }

        public Criteria andEnrollAccountNotIn(List<BigDecimal> values) {
            addCriterion("enroll_account not in", values, "enrollAccount");
            return (Criteria) this;
        }

        public Criteria andEnrollAccountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("enroll_account between", value1, value2, "enrollAccount");
            return (Criteria) this;
        }

        public Criteria andEnrollAccountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("enroll_account not between", value1, value2, "enrollAccount");
            return (Criteria) this;
        }

        public Criteria andPrepaidAmountIsNull() {
            addCriterion("prepaid_amount is null");
            return (Criteria) this;
        }

        public Criteria andPrepaidAmountIsNotNull() {
            addCriterion("prepaid_amount is not null");
            return (Criteria) this;
        }

        public Criteria andPrepaidAmountEqualTo(BigDecimal value) {
            addCriterion("prepaid_amount =", value, "prepaidAmount");
            return (Criteria) this;
        }

        public Criteria andPrepaidAmountNotEqualTo(BigDecimal value) {
            addCriterion("prepaid_amount <>", value, "prepaidAmount");
            return (Criteria) this;
        }

        public Criteria andPrepaidAmountGreaterThan(BigDecimal value) {
            addCriterion("prepaid_amount >", value, "prepaidAmount");
            return (Criteria) this;
        }

        public Criteria andPrepaidAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("prepaid_amount >=", value, "prepaidAmount");
            return (Criteria) this;
        }

        public Criteria andPrepaidAmountLessThan(BigDecimal value) {
            addCriterion("prepaid_amount <", value, "prepaidAmount");
            return (Criteria) this;
        }

        public Criteria andPrepaidAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("prepaid_amount <=", value, "prepaidAmount");
            return (Criteria) this;
        }

        public Criteria andPrepaidAmountIn(List<BigDecimal> values) {
            addCriterion("prepaid_amount in", values, "prepaidAmount");
            return (Criteria) this;
        }

        public Criteria andPrepaidAmountNotIn(List<BigDecimal> values) {
            addCriterion("prepaid_amount not in", values, "prepaidAmount");
            return (Criteria) this;
        }

        public Criteria andPrepaidAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("prepaid_amount between", value1, value2, "prepaidAmount");
            return (Criteria) this;
        }

        public Criteria andPrepaidAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("prepaid_amount not between", value1, value2, "prepaidAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountIsNull() {
            addCriterion("pay_amount is null");
            return (Criteria) this;
        }

        public Criteria andPayAmountIsNotNull() {
            addCriterion("pay_amount is not null");
            return (Criteria) this;
        }

        public Criteria andPayAmountEqualTo(BigDecimal value) {
            addCriterion("pay_amount =", value, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountNotEqualTo(BigDecimal value) {
            addCriterion("pay_amount <>", value, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountGreaterThan(BigDecimal value) {
            addCriterion("pay_amount >", value, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("pay_amount >=", value, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountLessThan(BigDecimal value) {
            addCriterion("pay_amount <", value, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("pay_amount <=", value, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountIn(List<BigDecimal> values) {
            addCriterion("pay_amount in", values, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountNotIn(List<BigDecimal> values) {
            addCriterion("pay_amount not in", values, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pay_amount between", value1, value2, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pay_amount not between", value1, value2, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayTimeIsNull() {
            addCriterion("pay_time is null");
            return (Criteria) this;
        }

        public Criteria andPayTimeIsNotNull() {
            addCriterion("pay_time is not null");
            return (Criteria) this;
        }

        public Criteria andPayTimeEqualTo(Date value) {
            addCriterion("pay_time =", value, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeNotEqualTo(Date value) {
            addCriterion("pay_time <>", value, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeGreaterThan(Date value) {
            addCriterion("pay_time >", value, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("pay_time >=", value, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeLessThan(Date value) {
            addCriterion("pay_time <", value, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeLessThanOrEqualTo(Date value) {
            addCriterion("pay_time <=", value, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeIn(List<Date> values) {
            addCriterion("pay_time in", values, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeNotIn(List<Date> values) {
            addCriterion("pay_time not in", values, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeBetween(Date value1, Date value2) {
            addCriterion("pay_time between", value1, value2, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeNotBetween(Date value1, Date value2) {
            addCriterion("pay_time not between", value1, value2, "payTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ych_enroll
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ych_enroll
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}