package com.xqx.ych.entity;

import java.io.Serializable;

public class Major implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ych_major.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ych_major.major_code
     *
     * @mbggenerated
     */
    private Integer majorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ych_major.major_name
     *
     * @mbggenerated
     */
    private String majorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ych_major.major_description
     *
     * @mbggenerated
     */
    private String majorDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ych_major.major_category_id
     *
     * @mbggenerated
     */
    private Integer majorCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ych_major
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ych_major.id
     *
     * @return the value of ych_major.id
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ych_major.id
     *
     * @param id the value for ych_major.id
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ych_major.major_code
     *
     * @return the value of ych_major.major_code
     * @mbggenerated
     */
    public Integer getMajorCode() {
        return majorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ych_major.major_code
     *
     * @param majorCode the value for ych_major.major_code
     * @mbggenerated
     */
    public void setMajorCode(Integer majorCode) {
        this.majorCode = majorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ych_major.major_name
     *
     * @return the value of ych_major.major_name
     * @mbggenerated
     */
    public String getMajorName() {
        return majorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ych_major.major_name
     *
     * @param majorName the value for ych_major.major_name
     * @mbggenerated
     */
    public void setMajorName(String majorName) {
        this.majorName = majorName == null ? null : majorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ych_major.major_description
     *
     * @return the value of ych_major.major_description
     * @mbggenerated
     */
    public String getMajorDescription() {
        return majorDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ych_major.major_description
     *
     * @param majorDescription the value for ych_major.major_description
     * @mbggenerated
     */
    public void setMajorDescription(String majorDescription) {
        this.majorDescription = majorDescription == null ? null : majorDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ych_major.major_category_id
     *
     * @return the value of ych_major.major_category_id
     * @mbggenerated
     */
    public Integer getMajorCategoryId() {
        return majorCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ych_major.major_category_id
     *
     * @param majorCategoryId the value for ych_major.major_category_id
     * @mbggenerated
     */
    public void setMajorCategoryId(Integer majorCategoryId) {
        this.majorCategoryId = majorCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_major
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", majorCode=").append(majorCode);
        sb.append(", majorName=").append(majorName);
        sb.append(", majorDescription=").append(majorDescription);
        sb.append(", majorCategoryId=").append(majorCategoryId);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_major
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Major other = (Major) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getMajorCode() == null ? other.getMajorCode() == null : this.getMajorCode().equals(other.getMajorCode()))
                && (this.getMajorName() == null ? other.getMajorName() == null : this.getMajorName().equals(other.getMajorName()))
                && (this.getMajorDescription() == null ? other.getMajorDescription() == null : this.getMajorDescription().equals(other.getMajorDescription()))
                && (this.getMajorCategoryId() == null ? other.getMajorCategoryId() == null : this.getMajorCategoryId().equals(other.getMajorCategoryId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_major
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getMajorCode() == null) ? 0 : getMajorCode().hashCode());
        result = prime * result + ((getMajorName() == null) ? 0 : getMajorName().hashCode());
        result = prime * result + ((getMajorDescription() == null) ? 0 : getMajorDescription().hashCode());
        result = prime * result + ((getMajorCategoryId() == null) ? 0 : getMajorCategoryId().hashCode());
        return result;
    }
}