package com.xqx.ych.entity;

import java.io.Serializable;
import java.util.Date;

public class MajorNumberLog implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ych_major_number_log.major_number
     *
     * @mbggenerated
     */
    private Integer majorNumber;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ych_major_number_log.major_id
     *
     * @mbggenerated
     */
    private Integer majorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ych_major_number_log.org_id
     *
     * @mbggenerated
     */
    private Integer orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ych_major_number_log.enroll_id
     *
     * @mbggenerated
     */
    private String enrollId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ych_major_number_log.number_log_type
     *
     * @mbggenerated
     */
    private String numberLogType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ych_major_number_log.log_time
     *
     * @mbggenerated
     */
    private Date logTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ych_major_number_log
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ych_major_number_log.major_number
     *
     * @return the value of ych_major_number_log.major_number
     * @mbggenerated
     */
    public Integer getMajorNumber() {
        return majorNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ych_major_number_log.major_number
     *
     * @param majorNumber the value for ych_major_number_log.major_number
     * @mbggenerated
     */
    public void setMajorNumber(Integer majorNumber) {
        this.majorNumber = majorNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ych_major_number_log.number_log_type
     *
     * @return the value of ych_major_number_log.number_log_type
     * @mbggenerated
     */
    public String getNumberLogType() {
        return numberLogType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ych_major_number_log.number_log_type
     *
     * @param numberLogType the value for ych_major_number_log.number_log_type
     * @mbggenerated
     */
    public void setNumberLogType(String numberLogType) {
        this.numberLogType = numberLogType == null ? null : numberLogType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ych_major_number_log.log_time
     *
     * @return the value of ych_major_number_log.log_time
     * @mbggenerated
     */
    public Date getLogTime() {
        return logTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ych_major_number_log.log_time
     *
     * @param logTime the value for ych_major_number_log.log_time
     * @mbggenerated
     */
    public void setLogTime(Date logTime) {
        this.logTime = logTime;
    }

    public Integer getMajorId() {
        return majorId;
    }

    public void setMajorId(Integer majorId) {
        this.majorId = majorId;
    }

    public Integer getOrgId() {
        return orgId;
    }

    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    public String getEnrollId() {
        return enrollId;
    }

    public void setEnrollId(String enrollId) {
        this.enrollId = enrollId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_major_number_log
     *
     * @mbggenerated
     */

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", majorId=").append(majorId);
        sb.append(", orgId=").append(orgId);
        sb.append(", enrollId=").append(enrollId);
        sb.append(", majorNumber=").append(majorNumber);
        sb.append(", numberLogType=").append(numberLogType);
        sb.append(", logTime=").append(logTime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_major_number_log
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MajorNumberLog other = (MajorNumberLog) that;
        return (this.getMajorId() == null ? other.getMajorId() == null : this.getMajorId().equals(other.getMajorId()))
                && (this.getOrgId() == null ? other.getOrgId() == null : this.getOrgId().equals(other.getOrgId()))
                && (this.getEnrollId() == null ? other.getEnrollId() == null : this.getEnrollId().equals(other.getEnrollId()))
                && (this.getMajorNumber() == null ? other.getMajorNumber() == null : this.getMajorNumber().equals(other.getMajorNumber()))
                && (this.getNumberLogType() == null ? other.getNumberLogType() == null : this.getNumberLogType().equals(other.getNumberLogType()))
                && (this.getLogTime() == null ? other.getLogTime() == null : this.getLogTime().equals(other.getLogTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_major_number_log
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getMajorId() == null) ? 0 : getMajorId().hashCode());
        result = prime * result + ((getOrgId() == null) ? 0 : getOrgId().hashCode());
        result = prime * result + ((getEnrollId() == null) ? 0 : getEnrollId().hashCode());
        result = prime * result + ((getMajorNumber() == null) ? 0 : getMajorNumber().hashCode());
        result = prime * result + ((getNumberLogType() == null) ? 0 : getNumberLogType().hashCode());
        result = prime * result + ((getLogTime() == null) ? 0 : getLogTime().hashCode());
        return result;
    }
}