package com.xqx.ych.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class OrgMajor implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ych_org_major.enrollment_quota
     *
     * @mbggenerated
     */
    private Integer enrollmentQuota;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ych_org_major.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ych_org_major.org_id
     *
     * @mbggenerated
     */
    private Integer orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ych_org_major.major_id
     *
     * @mbggenerated
     */
    private Integer majorId;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ych_org_major.tuition
     *
     * @mbggenerated
     */
    private BigDecimal tuition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ych_org_major.pre_tuition
     *
     * @mbggenerated
     */
    private BigDecimal preTuition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ych_org_major.grant
     *
     * @mbggenerated
     */
    private BigDecimal grant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ych_org_major.is_hot
     *
     * @mbggenerated
     */
    private Integer isHot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ych_org_major
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    public OrgMajor() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ych_org_major.enrollment_quota
     *
     * @return the value of ych_org_major.enrollment_quota
     * @mbggenerated
     */
    public Integer getEnrollmentQuota() {
        return enrollmentQuota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ych_org_major.enrollment_quota
     *
     * @param enrollmentQuota the value for ych_org_major.enrollment_quota
     * @mbggenerated
     */
    public void setEnrollmentQuota(Integer enrollmentQuota) {
        this.enrollmentQuota = enrollmentQuota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ych_org_major.tuition
     *
     * @return the value of ych_org_major.tuition
     * @mbggenerated
     */
    public BigDecimal getTuition() {
        return tuition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ych_org_major.tuition
     *
     * @param tuition the value for ych_org_major.tuition
     * @mbggenerated
     */
    public void setTuition(BigDecimal tuition) {
        this.tuition = tuition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ych_org_major.pre_tuition
     *
     * @return the value of ych_org_major.pre_tuition
     * @mbggenerated
     */
    public BigDecimal getPreTuition() {
        return preTuition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ych_org_major.pre_tuition
     *
     * @param preTuition the value for ych_org_major.pre_tuition
     * @mbggenerated
     */
    public void setPreTuition(BigDecimal preTuition) {
        this.preTuition = preTuition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ych_org_major.grant
     *
     * @return the value of ych_org_major.grant
     * @mbggenerated
     */
    public BigDecimal getGrant() {
        return grant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ych_org_major.grant
     *
     * @param grant the value for ych_org_major.grant
     * @mbggenerated
     */
    public void setGrant(BigDecimal grant) {
        this.grant = grant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ych_org_major.is_hot
     *
     * @return the value of ych_org_major.is_hot
     * @mbggenerated
     */
    public Integer getIsHot() {
        return isHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ych_org_major.is_hot
     *
     * @param isHot the value for ych_org_major.is_hot
     * @mbggenerated
     */
    public void setIsHot(Integer isHot) {
        this.isHot = isHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_major
     *
     * @mbggenerated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ych_org_major.id
     *
     * @return the value of ych_org_major.id
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ych_org_major.id
     *
     * @param id the value for ych_org_major.id
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ych_org_major.org_id
     *
     * @return the value of ych_org_major.org_id
     * @mbggenerated
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ych_org_major.org_id
     *
     * @param orgId the value for ych_org_major.org_id
     * @mbggenerated
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ych_org_major.major_id
     *
     * @return the value of ych_org_major.major_id
     * @mbggenerated
     */
    public Integer getMajorId() {
        return majorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ych_org_major.major_id
     *
     * @param majorId the value for ych_org_major.major_id
     * @mbggenerated
     */
    public void setMajorId(Integer majorId) {
        this.majorId = majorId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", orgId=").append(orgId);
        sb.append(", majorId=").append(majorId);
        sb.append(", enrollmentQuota=").append(enrollmentQuota);
        sb.append(", tuition=").append(tuition);
        sb.append(", preTuition=").append(preTuition);
        sb.append(", grant=").append(grant);
        sb.append(", isHot=").append(isHot);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_major
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        OrgMajor other = (OrgMajor) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getOrgId() == null ? other.getOrgId() == null : this.getOrgId().equals(other.getOrgId()))
                && (this.getMajorId() == null ? other.getMajorId() == null : this.getMajorId().equals(other.getMajorId()))
                && (this.getEnrollmentQuota() == null ? other.getEnrollmentQuota() == null : this.getEnrollmentQuota().equals(other.getEnrollmentQuota()))
                && (this.getTuition() == null ? other.getTuition() == null : this.getTuition().equals(other.getTuition()))
                && (this.getPreTuition() == null ? other.getPreTuition() == null : this.getPreTuition().equals(other.getPreTuition()))
                && (this.getGrant() == null ? other.getGrant() == null : this.getGrant().equals(other.getGrant()))
                && (this.getIsHot() == null ? other.getIsHot() == null : this.getIsHot().equals(other.getIsHot()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_major
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOrgId() == null) ? 0 : getOrgId().hashCode());
        result = prime * result + ((getMajorId() == null) ? 0 : getMajorId().hashCode());
        result = prime * result + ((getEnrollmentQuota() == null) ? 0 : getEnrollmentQuota().hashCode());
        result = prime * result + ((getTuition() == null) ? 0 : getTuition().hashCode());
        result = prime * result + ((getPreTuition() == null) ? 0 : getPreTuition().hashCode());
        result = prime * result + ((getGrant() == null) ? 0 : getGrant().hashCode());
        result = prime * result + ((getIsHot() == null) ? 0 : getIsHot().hashCode());
        return result;
    }
}