package com.xqx.ych.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class User implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ych_user.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ych_user.user_nickname
     *
     * @mbggenerated
     */
    private String userNickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ych_user.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ych_user.user_email
     *
     * @mbggenerated
     */
    private String userEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ych_user.user_password
     *
     * @mbggenerated
     */
    private String userPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ych_user.salt
     *
     * @mbggenerated
     */
    private String salt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ych_user.user_mobile
     *
     * @mbggenerated
     */
    private String userMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ych_user.head_image
     *
     * @mbggenerated
     */
    private String headImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ych_user.user_score
     *
     * @mbggenerated
     */
    private Integer userScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ych_user.opened_func
     *
     * @mbggenerated
     */
    private Integer openedFunc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ych_user.school
     *
     * @mbggenerated
     */
    private String school;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ych_user.idCard
     *
     * @mbggenerated
     */
    private String idcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ych_user.native_place
     *
     * @mbggenerated
     */
    private String nativePlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ych_user.user_sex
     *
     * @mbggenerated
     */
    private String userSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ych_user.credits
     *
     * @mbggenerated
     */
    private String credits;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ych_user.discription
     *
     * @mbggenerated
     */
    private String discription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ych_user.user_reg_time
     *
     * @mbggenerated
     */
    private Date userRegTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ych_user.user_money
     *
     * @mbggenerated
     */
    private BigDecimal userMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ych_user.user_type
     *
     * @mbggenerated
     */
    private Integer userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ych_user.recruit_service_status
     *
     * @mbggenerated
     */
    private String recruitServiceStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ych_user.zhaosheng_service_status
     *
     * @mbggenerated
     */
    private String zhaoshengServiceStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ych_user.ycy_service_status
     *
     * @mbggenerated
     */
    private String ycyServiceStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ych_user
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ych_user.user_id
     *
     * @return the value of ych_user.user_id
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ych_user.user_id
     *
     * @param userId the value for ych_user.user_id
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ych_user.user_nickname
     *
     * @return the value of ych_user.user_nickname
     * @mbggenerated
     */
    public String getUserNickname() {
        return userNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ych_user.user_nickname
     *
     * @param userNickname the value for ych_user.user_nickname
     * @mbggenerated
     */
    public void setUserNickname(String userNickname) {
        this.userNickname = userNickname == null ? null : userNickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ych_user.user_name
     *
     * @return the value of ych_user.user_name
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ych_user.user_name
     *
     * @param userName the value for ych_user.user_name
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ych_user.user_email
     *
     * @return the value of ych_user.user_email
     * @mbggenerated
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ych_user.user_email
     *
     * @param userEmail the value for ych_user.user_email
     * @mbggenerated
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ych_user.user_password
     *
     * @return the value of ych_user.user_password
     * @mbggenerated
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ych_user.user_password
     *
     * @param userPassword the value for ych_user.user_password
     * @mbggenerated
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ych_user.salt
     *
     * @return the value of ych_user.salt
     * @mbggenerated
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ych_user.salt
     *
     * @param salt the value for ych_user.salt
     * @mbggenerated
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ych_user.user_mobile
     *
     * @return the value of ych_user.user_mobile
     * @mbggenerated
     */
    public String getUserMobile() {
        return userMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ych_user.user_mobile
     *
     * @param userMobile the value for ych_user.user_mobile
     * @mbggenerated
     */
    public void setUserMobile(String userMobile) {
        this.userMobile = userMobile == null ? null : userMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ych_user.head_image
     *
     * @return the value of ych_user.head_image
     * @mbggenerated
     */
    public String getHeadImage() {
        return headImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ych_user.head_image
     *
     * @param headImage the value for ych_user.head_image
     * @mbggenerated
     */
    public void setHeadImage(String headImage) {
        this.headImage = headImage == null ? null : headImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ych_user.user_score
     *
     * @return the value of ych_user.user_score
     * @mbggenerated
     */
    public Integer getUserScore() {
        return userScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ych_user.user_score
     *
     * @param userScore the value for ych_user.user_score
     * @mbggenerated
     */
    public void setUserScore(Integer userScore) {
        this.userScore = userScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ych_user.opened_func
     *
     * @return the value of ych_user.opened_func
     * @mbggenerated
     */
    public Integer getOpenedFunc() {
        return openedFunc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ych_user.opened_func
     *
     * @param openedFunc the value for ych_user.opened_func
     * @mbggenerated
     */
    public void setOpenedFunc(Integer openedFunc) {
        this.openedFunc = openedFunc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ych_user.school
     *
     * @return the value of ych_user.school
     * @mbggenerated
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ych_user.school
     *
     * @param school the value for ych_user.school
     * @mbggenerated
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ych_user.idCard
     *
     * @return the value of ych_user.idCard
     * @mbggenerated
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ych_user.idCard
     *
     * @param idcard the value for ych_user.idCard
     * @mbggenerated
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ych_user.native_place
     *
     * @return the value of ych_user.native_place
     * @mbggenerated
     */
    public String getNativePlace() {
        return nativePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ych_user.native_place
     *
     * @param nativePlace the value for ych_user.native_place
     * @mbggenerated
     */
    public void setNativePlace(String nativePlace) {
        this.nativePlace = nativePlace == null ? null : nativePlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ych_user.user_sex
     *
     * @return the value of ych_user.user_sex
     * @mbggenerated
     */
    public String getUserSex() {
        return userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ych_user.user_sex
     *
     * @param userSex the value for ych_user.user_sex
     * @mbggenerated
     */
    public void setUserSex(String userSex) {
        this.userSex = userSex == null ? null : userSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ych_user.credits
     *
     * @return the value of ych_user.credits
     * @mbggenerated
     */
    public String getCredits() {
        return credits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ych_user.credits
     *
     * @param credits the value for ych_user.credits
     * @mbggenerated
     */
    public void setCredits(String credits) {
        this.credits = credits == null ? null : credits.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ych_user.discription
     *
     * @return the value of ych_user.discription
     * @mbggenerated
     */
    public String getDiscription() {
        return discription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ych_user.discription
     *
     * @param discription the value for ych_user.discription
     * @mbggenerated
     */
    public void setDiscription(String discription) {
        this.discription = discription == null ? null : discription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ych_user.user_reg_time
     *
     * @return the value of ych_user.user_reg_time
     * @mbggenerated
     */
    public Date getUserRegTime() {
        return userRegTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ych_user.user_reg_time
     *
     * @param userRegTime the value for ych_user.user_reg_time
     * @mbggenerated
     */
    public void setUserRegTime(Date userRegTime) {
        this.userRegTime = userRegTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ych_user.user_money
     *
     * @return the value of ych_user.user_money
     * @mbggenerated
     */
    public BigDecimal getUserMoney() {
        return userMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ych_user.user_money
     *
     * @param userMoney the value for ych_user.user_money
     * @mbggenerated
     */
    public void setUserMoney(BigDecimal userMoney) {
        this.userMoney = userMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ych_user.user_type
     *
     * @return the value of ych_user.user_type
     * @mbggenerated
     */
    public Integer getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ych_user.user_type
     *
     * @param userType the value for ych_user.user_type
     * @mbggenerated
     */
    public void setUserType(Integer userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ych_user.recruit_service_status
     *
     * @return the value of ych_user.recruit_service_status
     * @mbggenerated
     */
    public String getRecruitServiceStatus() {
        return recruitServiceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ych_user.recruit_service_status
     *
     * @param recruitServiceStatus the value for ych_user.recruit_service_status
     * @mbggenerated
     */
    public void setRecruitServiceStatus(String recruitServiceStatus) {
        this.recruitServiceStatus = recruitServiceStatus == null ? null : recruitServiceStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ych_user.zhaosheng_service_status
     *
     * @return the value of ych_user.zhaosheng_service_status
     * @mbggenerated
     */
    public String getZhaoshengServiceStatus() {
        return zhaoshengServiceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ych_user.zhaosheng_service_status
     *
     * @param zhaoshengServiceStatus the value for ych_user.zhaosheng_service_status
     * @mbggenerated
     */
    public void setZhaoshengServiceStatus(String zhaoshengServiceStatus) {
        this.zhaoshengServiceStatus = zhaoshengServiceStatus == null ? null : zhaoshengServiceStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ych_user.ycy_service_status
     *
     * @return the value of ych_user.ycy_service_status
     * @mbggenerated
     */
    public String getYcyServiceStatus() {
        return ycyServiceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ych_user.ycy_service_status
     *
     * @param ycyServiceStatus the value for ych_user.ycy_service_status
     * @mbggenerated
     */
    public void setYcyServiceStatus(String ycyServiceStatus) {
        this.ycyServiceStatus = ycyServiceStatus == null ? null : ycyServiceStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_user
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", userNickname=").append(userNickname);
        sb.append(", userName=").append(userName);
        sb.append(", userEmail=").append(userEmail);
        sb.append(", userPassword=").append(userPassword);
        sb.append(", salt=").append(salt);
        sb.append(", userMobile=").append(userMobile);
        sb.append(", headImage=").append(headImage);
        sb.append(", userScore=").append(userScore);
        sb.append(", openedFunc=").append(openedFunc);
        sb.append(", school=").append(school);
        sb.append(", idcard=").append(idcard);
        sb.append(", nativePlace=").append(nativePlace);
        sb.append(", userSex=").append(userSex);
        sb.append(", credits=").append(credits);
        sb.append(", discription=").append(discription);
        sb.append(", userRegTime=").append(userRegTime);
        sb.append(", userMoney=").append(userMoney);
        sb.append(", userType=").append(userType);
        sb.append(", recruitServiceStatus=").append(recruitServiceStatus);
        sb.append(", zhaoshengServiceStatus=").append(zhaoshengServiceStatus);
        sb.append(", ycyServiceStatus=").append(ycyServiceStatus);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_user
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        User other = (User) that;
        return (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
                && (this.getUserNickname() == null ? other.getUserNickname() == null : this.getUserNickname().equals(other.getUserNickname()))
                && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
                && (this.getUserEmail() == null ? other.getUserEmail() == null : this.getUserEmail().equals(other.getUserEmail()))
                && (this.getUserPassword() == null ? other.getUserPassword() == null : this.getUserPassword().equals(other.getUserPassword()))
                && (this.getSalt() == null ? other.getSalt() == null : this.getSalt().equals(other.getSalt()))
                && (this.getUserMobile() == null ? other.getUserMobile() == null : this.getUserMobile().equals(other.getUserMobile()))
                && (this.getHeadImage() == null ? other.getHeadImage() == null : this.getHeadImage().equals(other.getHeadImage()))
                && (this.getUserScore() == null ? other.getUserScore() == null : this.getUserScore().equals(other.getUserScore()))
                && (this.getOpenedFunc() == null ? other.getOpenedFunc() == null : this.getOpenedFunc().equals(other.getOpenedFunc()))
                && (this.getSchool() == null ? other.getSchool() == null : this.getSchool().equals(other.getSchool()))
                && (this.getIdcard() == null ? other.getIdcard() == null : this.getIdcard().equals(other.getIdcard()))
                && (this.getNativePlace() == null ? other.getNativePlace() == null : this.getNativePlace().equals(other.getNativePlace()))
                && (this.getUserSex() == null ? other.getUserSex() == null : this.getUserSex().equals(other.getUserSex()))
                && (this.getCredits() == null ? other.getCredits() == null : this.getCredits().equals(other.getCredits()))
                && (this.getDiscription() == null ? other.getDiscription() == null : this.getDiscription().equals(other.getDiscription()))
                && (this.getUserRegTime() == null ? other.getUserRegTime() == null : this.getUserRegTime().equals(other.getUserRegTime()))
                && (this.getUserMoney() == null ? other.getUserMoney() == null : this.getUserMoney().equals(other.getUserMoney()))
                && (this.getUserType() == null ? other.getUserType() == null : this.getUserType().equals(other.getUserType()))
                && (this.getRecruitServiceStatus() == null ? other.getRecruitServiceStatus() == null : this.getRecruitServiceStatus().equals(other.getRecruitServiceStatus()))
                && (this.getZhaoshengServiceStatus() == null ? other.getZhaoshengServiceStatus() == null : this.getZhaoshengServiceStatus().equals(other.getZhaoshengServiceStatus()))
                && (this.getYcyServiceStatus() == null ? other.getYcyServiceStatus() == null : this.getYcyServiceStatus().equals(other.getYcyServiceStatus()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_user
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getUserNickname() == null) ? 0 : getUserNickname().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getUserEmail() == null) ? 0 : getUserEmail().hashCode());
        result = prime * result + ((getUserPassword() == null) ? 0 : getUserPassword().hashCode());
        result = prime * result + ((getSalt() == null) ? 0 : getSalt().hashCode());
        result = prime * result + ((getUserMobile() == null) ? 0 : getUserMobile().hashCode());
        result = prime * result + ((getHeadImage() == null) ? 0 : getHeadImage().hashCode());
        result = prime * result + ((getUserScore() == null) ? 0 : getUserScore().hashCode());
        result = prime * result + ((getOpenedFunc() == null) ? 0 : getOpenedFunc().hashCode());
        result = prime * result + ((getSchool() == null) ? 0 : getSchool().hashCode());
        result = prime * result + ((getIdcard() == null) ? 0 : getIdcard().hashCode());
        result = prime * result + ((getNativePlace() == null) ? 0 : getNativePlace().hashCode());
        result = prime * result + ((getUserSex() == null) ? 0 : getUserSex().hashCode());
        result = prime * result + ((getCredits() == null) ? 0 : getCredits().hashCode());
        result = prime * result + ((getDiscription() == null) ? 0 : getDiscription().hashCode());
        result = prime * result + ((getUserRegTime() == null) ? 0 : getUserRegTime().hashCode());
        result = prime * result + ((getUserMoney() == null) ? 0 : getUserMoney().hashCode());
        result = prime * result + ((getUserType() == null) ? 0 : getUserType().hashCode());
        result = prime * result + ((getRecruitServiceStatus() == null) ? 0 : getRecruitServiceStatus().hashCode());
        result = prime * result + ((getZhaoshengServiceStatus() == null) ? 0 : getZhaoshengServiceStatus().hashCode());
        result = prime * result + ((getYcyServiceStatus() == null) ? 0 : getYcyServiceStatus().hashCode());
        return result;
    }
}