package com.xqx.ych.mapper;

import com.xqx.ych.entity.Enroll;
import com.xqx.ych.entity.EnrollExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface EnrollMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_enroll
     *
     * @mbggenerated
     */
    int countByExample(EnrollExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_enroll
     *
     * @mbggenerated
     */
    int deleteByExample(EnrollExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_enroll
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String enrollId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_enroll
     *
     * @mbggenerated
     */
    int insert(Enroll record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_enroll
     *
     * @mbggenerated
     */
    int insertSelective(Enroll record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_enroll
     *
     * @mbggenerated
     */
    List<Enroll> selectByExample(EnrollExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_enroll
     *
     * @mbggenerated
     */
    Enroll selectByPrimaryKey(String enrollId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_enroll
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Enroll record, @Param("example") EnrollExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_enroll
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Enroll record, @Param("example") EnrollExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_enroll
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Enroll record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_enroll
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Enroll record);
}