package com.xqx.ych.mapper;

import com.xqx.ych.entity.MajorCategory;
import com.xqx.ych.entity.MajorCategoryExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface MajorCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_major_category
     *
     * @mbggenerated
     */
    int countByExample(MajorCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_major_category
     *
     * @mbggenerated
     */
    int deleteByExample(MajorCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_major_category
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_major_category
     *
     * @mbggenerated
     */
    int insert(MajorCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_major_category
     *
     * @mbggenerated
     */
    int insertSelective(MajorCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_major_category
     *
     * @mbggenerated
     */
    List<MajorCategory> selectByExample(MajorCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_major_category
     *
     * @mbggenerated
     */
    MajorCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_major_category
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MajorCategory record, @Param("example") MajorCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_major_category
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MajorCategory record, @Param("example") MajorCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_major_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MajorCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_major_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MajorCategory record);
}