package com.xqx.ych.mapper;

import com.xqx.ych.entity.Major;
import com.xqx.ych.entity.MajorExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface MajorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_major
     *
     * @mbggenerated
     */
    int countByExample(MajorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_major
     *
     * @mbggenerated
     */
    int deleteByExample(MajorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_major
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_major
     *
     * @mbggenerated
     */
    int insert(Major record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_major
     *
     * @mbggenerated
     */
    int insertSelective(Major record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_major
     *
     * @mbggenerated
     */
    List<Major> selectByExample(MajorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_major
     *
     * @mbggenerated
     */
    Major selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_major
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Major record, @Param("example") MajorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_major
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Major record, @Param("example") MajorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_major
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Major record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_major
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Major record);
}