package com.xqx.ych.mapper;

import com.xqx.ych.entity.OrgAddress;
import com.xqx.ych.entity.OrgAddressExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OrgAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_address
     *
     * @mbggenerated
     */
    int countByExample(OrgAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_address
     *
     * @mbggenerated
     */
    int deleteByExample(OrgAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_address
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_address
     *
     * @mbggenerated
     */
    int insert(OrgAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_address
     *
     * @mbggenerated
     */
    int insertSelective(OrgAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_address
     *
     * @mbggenerated
     */
    List<OrgAddress> selectByExampleWithBLOBs(OrgAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_address
     *
     * @mbggenerated
     */
    List<OrgAddress> selectByExample(OrgAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_address
     *
     * @mbggenerated
     */
    OrgAddress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_address
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OrgAddress record, @Param("example") OrgAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_address
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") OrgAddress record, @Param("example") OrgAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_address
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OrgAddress record, @Param("example") OrgAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_address
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrgAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_address
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(OrgAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_address
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrgAddress record);

    OrgAddress findByOrgId(@Param("orgId") Integer orgId);
}