package com.xqx.ych.mapper;

import com.xqx.ych.entity.OrgDynamic;
import com.xqx.ych.entity.OrgDynamicExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface OrgDynamicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_dynamic
     *
     * @mbggenerated
     */
    int countByExample(OrgDynamicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_dynamic
     *
     * @mbggenerated
     */
    int deleteByExample(OrgDynamicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_dynamic
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_dynamic
     *
     * @mbggenerated
     */
    int insert(OrgDynamic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_dynamic
     *
     * @mbggenerated
     */
    int insertSelective(OrgDynamic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_dynamic
     *
     * @mbggenerated
     */
    List<OrgDynamic> selectByExampleWithBLOBs(OrgDynamicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_dynamic
     *
     * @mbggenerated
     */
    List<OrgDynamic> selectByExample(OrgDynamicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_dynamic
     *
     * @mbggenerated
     */
    OrgDynamic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_dynamic
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OrgDynamic record, @Param("example") OrgDynamicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_dynamic
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") OrgDynamic record, @Param("example") OrgDynamicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_dynamic
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OrgDynamic record, @Param("example") OrgDynamicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_dynamic
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrgDynamic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_dynamic
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(OrgDynamic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_dynamic
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrgDynamic record);
}