package com.xqx.ych.mapper;

import com.xqx.ych.entity.OrgIntroduce;
import com.xqx.ych.entity.OrgIntroduceExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OrgIntroduceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_introduce
     *
     * @mbggenerated
     */
    int countByExample(OrgIntroduceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_introduce
     *
     * @mbggenerated
     */
    int deleteByExample(OrgIntroduceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_introduce
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_introduce
     *
     * @mbggenerated
     */
    int insert(OrgIntroduce record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_introduce
     *
     * @mbggenerated
     */
    int insertSelective(@Param("detail") String detail);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_introduce
     *
     * @mbggenerated
     */
    List<OrgIntroduce> selectByExampleWithBLOBs(OrgIntroduceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_introduce
     *
     * @mbggenerated
     */
    List<OrgIntroduce> selectByExample(OrgIntroduceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_introduce
     *
     * @mbggenerated
     */
    OrgIntroduce selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_introduce
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OrgIntroduce record, @Param("example") OrgIntroduceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_introduce
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") OrgIntroduce record, @Param("example") OrgIntroduceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_introduce
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OrgIntroduce record, @Param("example") OrgIntroduceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_introduce
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrgIntroduce record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_introduce
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(OrgIntroduce record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_introduce
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrgIntroduce record);
}