package com.xqx.ych.mapper;

import com.xqx.ych.entity.*;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OrgMajorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_major
     *
     * @mbggenerated
     */
    int countByExample(OrgMajorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_major
     *
     * @mbggenerated
     */
    int deleteByExample(OrgMajorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_major
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(OrgMajorKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_major
     *
     * @mbggenerated
     */
    int insert(OrgMajor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_major
     *
     * @mbggenerated
     */
    int insertSelective(OrgMajor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_major
     *
     * @mbggenerated
     */
    List<OrgMajor> selectByExample(OrgMajorExample example);

    List<OrgMajor> selectByOrgMajorId(@Param("id") Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_major
     *
     * @mbggenerated
     */
    OrgMajor selectByPrimaryKey(OrgMajorKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_major
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OrgMajor record, @Param("example") OrgMajorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_major
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OrgMajor record, @Param("example") OrgMajorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_major
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrgMajor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_major
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrgMajor record);

    List<SchoolInfo> selectByMajorId(@Param("majorId") Integer majorId);

    SchoolIntroduce findByIdAndMajor(@Param("id") Integer id, @Param("majorId") Integer majorId);

    List<Major> findByPop(@Param("isHot") Integer isHot);

    List<OrgMajor> findByOrgId(@Param("orgId") Integer id);

    /**
     * 增加库存
     *
     * @return
     */
    int addQuot(@Param("id") Integer id, @Param("quot") Integer quot);

    /**
     * 减少库存
     *
     * @return
     */
    int reduceQuot(@Param("id") Integer id, @Param("quot") Integer quot);

    UserEnroll findByOrgMajorId(@Param("orgMajorId") Integer orgMajorId);

    UserEnroll findCouponByUserId(@Param("userId") Integer userId);

    UserEnroll findUserNameById(@Param("userId") Integer userId);
}