package com.xqx.ych.mapper;

import com.xqx.ych.entity.OrgVideoIntroduce;
import com.xqx.ych.entity.OrgVideoIntroduceExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface OrgVideoIntroduceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_video_introduce
     *
     * @mbggenerated
     */
    int countByExample(OrgVideoIntroduceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_video_introduce
     *
     * @mbggenerated
     */
    int deleteByExample(OrgVideoIntroduceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_video_introduce
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_video_introduce
     *
     * @mbggenerated
     */
    int insert(OrgVideoIntroduce record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_video_introduce
     *
     * @mbggenerated
     */
    int insertSelective(OrgVideoIntroduce record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_video_introduce
     *
     * @mbggenerated
     */
    List<OrgVideoIntroduce> selectByExample(OrgVideoIntroduceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_video_introduce
     *
     * @mbggenerated
     */
    OrgVideoIntroduce selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_video_introduce
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OrgVideoIntroduce record, @Param("example") OrgVideoIntroduceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_video_introduce
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OrgVideoIntroduce record, @Param("example") OrgVideoIntroduceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_video_introduce
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrgVideoIntroduce record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_org_video_introduce
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrgVideoIntroduce record);
}