package com.xqx.ych.mapper;

import com.xqx.ych.entity.Pay;
import com.xqx.ych.entity.PayExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_pay
     *
     * @mbggenerated
     */
    int countByExample(PayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_pay
     *
     * @mbggenerated
     */
    int deleteByExample(PayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_pay
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String payId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_pay
     *
     * @mbggenerated
     */
    int insert(Pay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_pay
     *
     * @mbggenerated
     */
    int insertSelective(Pay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_pay
     *
     * @mbggenerated
     */
    List<Pay> selectByExample(PayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_pay
     *
     * @mbggenerated
     */
    Pay selectByPrimaryKey(String payId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_pay
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Pay record, @Param("example") PayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_pay
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Pay record, @Param("example") PayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_pay
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Pay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_pay
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Pay record);

    int updateIsPaid(@Param("payId") String payId, @Param("isPaid") String isPaid);
}